package lexer;


public enum TokenType{
	INT,VOID,DOUBLE,BOOL,STRING,NOT,AND,OR,NE,LE,GE,EQ,GT,LT,TRUE,FALSE,BASICTYPE,IF,ELSE,WHILE,ASYNC,
	MINUS,PLUS,DIVIDED,TIMES,LEFT_PAREN,RIGHT_PAREN,LEFT_CURL,RIGHT_CURL,LEFT_SQURE_BRACE,RIGHT_SQUARE_BRACE,EOF,INVALID_CHAR,ASSIGN,ID,
	COMMA,SEMICOLON,RETURN,BREAK,CONTINUE,FUN,VAR,MAIN,PRINTLN,DASYNC;
	}